# Generated by Django 5.0.6 on 2024-07-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='records/', verbose_name='Изображение(превью)'),
        ),
    ]
